project:
  type: website
  output-dir: docs

website:
  title: "Chi Chi Okezie"
  bread-crumbs: true
  navbar:
    background: secondary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Projects
        menu: 
          - projects.qmd
          - tidytuesdays.qmd
      - href: experiences.qmd
        text: Leadership
      
        
  page-footer:
      left: |
        &copy; Chi Chi Okezie, 2026<br>
        All content licensed under <i class='bi-badge-cc'></i>
        [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
      right: |
        Site built with <a href='https://quarto.org/'>Quarto</a>

format:
  html:
    theme: lux
    css: styles.css
    toc: true


